Tweaked raster-filter if statements
I've changed all if statements to use the if [ condition ] style, and
removed the check that "$error" is not empty before sending an email,
since having convert fail implies an error message, which should be
emailed out. (Even with no error message, an email can still be sent,
indicating an error with the conversion.)

Note that I've also removed the -e option when setting Bash script
options, which allows me to better check the error status of convert.

diff --git a/modules/ocf/files/packages/cups/raster-filter b/modules/ocf/files/packages/cups/raster-filter
--- a/modules/ocf/files/packages/cups/raster-filter
+++ b/modules/ocf/files/packages/cups/raster-filter
@@ -3,7 +3,7 @@
 # A Tea4CUPS filter to perform rasterization.
 # Based off the pdf-open script
 
-set -euo pipefail
+set -uo pipefail
 
 input=$(mktemp --suffix='.pdf')
 
@@ -22,10 +22,11 @@ fi
 output=$(mktemp --suffix='.pdf')
 error=$(mktemp)
 
-if ! convert -density 250 "$input" "$output" 2> "$error"; then
-    if [ -s "$error" ]; then
-        cat "$error" | "/usr/local/bin/convert_failure"
-    fi
+convert -density 250 "$input" "$output" 2> "$error"
+
+# Check exit status of convert
+if [ "$?" -ne 0 ]; then
+    cat "$error" | "/usr/local/bin/convert_failure"
     cat "$input"
     exit
 fi
