Improved raster-filter, convert_failure
I've re-written convert_failure to place most of the program logic
inside a main function, as specified from some PR comments. I've also
added a check to reject any TTY input, in order to deter misuse of the
script.

I've slightly changed the logic in raster-filter as well, storing any
error message from convert in a tempfile, and then sending it to
convert_failure. This ensures ordering, since convert can take a while
to finish its job.

diff --git a/modules/ocf/files/packages/cups/raster-filter b/modules/ocf/files/packages/cups/raster-filter
--- a/modules/ocf/files/packages/cups/raster-filter
+++ b/modules/ocf/files/packages/cups/raster-filter
@@ -20,8 +20,12 @@ fi
 
 # Rasterizing PDF...
 output=$(mktemp --suffix='.pdf')
+error=$(mktemp)
 
-if ! convert -density 250 "$input" "$output" 2>&1 | "/usr/local/bin/convert_failure"; then
+if ! convert -density 250 "$input" "$output" 2> "$error"; then
+    if [ -s "$error" ]; then
+        cat "$error" | "/usr/local/bin/convert_failure"
+    fi
     cat "$input"
     exit
 fi
